development:
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  database: unusual_spending_development

test:
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  database: unusual_spending_test

production:
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  database: unusual_spending_production