default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  pool: <%= ENV.fetch('DB_POOL') { 15 } %>

development:
  <<: *default
  database: unusual_spending_development

test:
  <<: *default
  database: unusual_spending_test

production:
  <<: *default
  database: unusual_spending_production